# Generated by Django 5.2.10 on 2026-05-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_body'),
        ('home', '0003_alter_homepage_body'),
    ]

    operations = [
    ]
