# Generated by Django 5.2.14 on 2026-05-08 17:24

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_alter_articlepage_body_alter_articlepage_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticleFormat',
            fields=[
                ('articletopic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.articletopic')),
            ],
            bases=('utils.articletopic',),
        ),
        migrations.CreateModel(
            name='KnowledgeArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.articlepage')),
                ('search_keywords', models.TextField(blank=True)),
                ('article_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='knowledgeplatform.knowledgearticleformat')),
            ],
            options={
                'abstract': False,
            },
            bases=('news.articlepage',),
        ),
        migrations.CreateModel(
            name='KnowledgeArticleAttachedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_resources', to='knowledgeplatform.knowledgearticlepage')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='knowledgeplatform.knowledgearticlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='knowledgearticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='knowledgeplatform.KnowledgeArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
