# Generated by Django 5.2.14 on 2026-05-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0002_authorship_knowledgearticlepage_authors'),
        ('news', '0002_alter_articlepage_body_alter_articlepage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHubListingPage',
            fields=[
                ('newslistingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.newslistingpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('news.newslistingpage',),
        ),
    ]
