# Generated by Django 5.2.14 on 2026-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0003_knowledgehublistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticlepage',
            name='display_table_of_contents',
            field=models.BooleanField(default=True),
        ),
    ]
