# Generated by Django 5.2.14 on 2026-06-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0004_knowledgearticlepage_display_table_of_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticlepage',
            name='article_format',
        ),
        migrations.DeleteModel(
            name='KnowledgeArticleFormat',
        ),
    ]
