# Generated by Django 5.2.14 on 2026-06-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0005_remove_knowledgearticlepage_article_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticleFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgearticlepage',
            name='article_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='knowledgeplatform.knowledgearticleformat'),
        ),
    ]
