# Generated by Django 5.2.15 on 2026-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0006_knowledgearticleformat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticleformat',
            name='slug',
            field=models.SlugField(default='format', max_length=255),
            preserve_default=False,
        ),
    ]
