# Generated by Django 5.2.15 on 2026-06-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0007_knowledgearticleformat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticleLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgearticlepage',
            name='article_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='knowledgeplatform.knowledgearticlelicense'),
        ),
    ]
