# Generated by Django 5.2.15 on 2026-06-17 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0008_knowledgearticlelicense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehublistingpage',
            name='image',
            field=wagtail.fields.StreamField([('image', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('justify-start', 'Left'), ('justify-center', 'Center'), ('justify-end', 'Right'), ('justify-normal', 'Justify')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('image_alt_text', 1), ('caption', 2), ('align', 3)]], {})}),
        ),
    ]
