# Generated by Django 5.2.15 on 2026-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0009_knowledgehublistingpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehublistingpage',
            name='color_hex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
