# Generated by Django 5.2.15 on 2026-06-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0007_knowledgehublistingpage_color_hex'),
        ('knowledgeplatform', '0009_knowledgehublistingpage_image'),
    ]

    operations = [
    ]
