# Generated by Django 5.2.14 on 2026-06-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0010_knowledgehublistingpage_color_hex'),
        ('knowledgeplatform', '0011_knowledgehubtopicpage'),
    ]

    operations = [
    ]
