# Generated by Django 5.2.14 on 2026-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0013_knowledgehubhomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgehublistingpage',
            name='color_hex',
            field=models.CharField(blank=True, help_text='The background color for the CTA to this page on the homepage, expressed as any valid css colour string (eg #ff0000 or rgb(1, 2, 3))', max_length=10, null=True),
        ),
    ]
