# Generated by Django 5.2.14 on 2026-07-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0014_alter_knowledgehublistingpage_color_hex'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticleformat',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='knowledgearticleformat',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
