# Generated by Django 5.2.14 on 2026-07-06 17:14

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel

class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0015_knowledgearticleformat_locale_and_more'),
    ]

    operations = [
        BootstrapTranslatableModel('knowledgeplatform.KnowledgeArticleFormat'),
    ]
