# Generated by Django 5.2.14 on 2026-08-28 16:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('knowledgeplatform', '0020_knowledgehubsearchpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='mission_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='mission_title',
            field=models.CharField(default='Our mission and strategy', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='thematic_areas_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='thematic_areas_title',
            field=models.CharField(default='Thematic areas', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgehubtopicpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
