# Generated by Django 5.2.14 on 2026-08-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0020_knowledgehubsearchpage'),
        ('news', '0007_alter_articlepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCaseAttachedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCasePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.articlepage')),
                ('display_table_of_contents', models.BooleanField(default=True)),
                ('search_keywords', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('news.articlepage', models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeCaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
