# Generated by Django 5.2.14 on 2026-09-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0021_alter_knowledgehubsearchpage_appear_in_search_results'),
        ('knowledgeplatform', '0021_knowledgearticlecompliance_and_more'),
    ]

    operations = [
    ]
