# Generated by Django 5.2.14 on 2026-08-31 11:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0021_knowledgehubhomepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='resources_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='resources_title',
            field=models.CharField(default='more4nature resources', max_length=255),
        ),
    ]
