# Generated by Django 5.2.14 on 2026-08-25 10:37

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0021_casecontact_knowledgecaseattachedresource_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('utils', '0012_contactsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='utils.contactsnippet'),
        ),
        migrations.AddField(
            model_name='knowledgecasepage',
            name='case_contacts',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='knowledgeplatform.CaseContact', to='utils.contactsnippet'),
        ),
        migrations.AddField(
            model_name='knowledgecaseattachedresource',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_resources', to='knowledgeplatform.knowledgecasepage'),
        ),
        migrations.AddField(
            model_name='casecontact',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='knowledgeplatform.knowledgecasepage'),
        ),
        migrations.AddField(
            model_name='knowledgecasetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='knowledgeplatform.knowledgecasepage'),
        ),
        migrations.AddField(
            model_name='knowledgecasetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='knowledgecasepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='knowledgeplatform.KnowledgeCaseTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
