# Generated by Django 5.2.14 on 2026-08-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0022_casecontact_contact_knowledgecasepage_case_contacts_and_more'),
        ('news', '0007_alter_articlepage_body'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('utils', '0012_contactsnippet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeCasePage',
            new_name='KnowledgeHubCasePage',
        ),
    ]
