# Generated by Django 5.2.14 on 2026-08-31 14:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0022_knowledgehubhomepage_resources_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='discover_more_page',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1)]], {})}),
        ),
    ]
