# Generated by Django 5.2.14 on 2026-08-25 10:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0023_rename_knowledgecasepage_knowledgehubcasepage'),
        ('news', '0007_alter_articlepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHubCaseListingPage',
            fields=[
                ('newslistingpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.newslistingpage')),
                ('image', wagtail.fields.StreamField([('image', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('justify-start', 'Left'), ('justify-center', 'Center'), ('justify-end', 'Right'), ('justify-normal', 'Justify')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('image_alt_text', 1), ('caption', 2), ('align', 3)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('news.newslistingpage',),
        ),
    ]
