# Generated by Django 5.2.14 on 2026-08-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0024_knowledgehubcaselistingpage'),
        ('utils', '0013_casescopesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='utils.casescopesnippet'),
        ),
    ]
