# Generated by Django 5.2.14 on 2026-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0026_knowledgehubcasepage_display_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='location_label',
            field=models.CharField(blank=True, help_text='Place name — used both to search/geocode the map pin and shown publicly under the map', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='location_zoom',
            field=models.SmallIntegerField(blank=True, default=13, null=True),
        ),
    ]
