# Generated by Django 5.2.14 on 2026-08-26 10:25

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0027_knowledgehubcasepage_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='cgd_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='policy_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knowledgehubcasepage',
            name='location_label',
            field=models.CharField(blank=True, help_text='Place name. Used both to search/geocode the pin on the map and shown publicly on the page', max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgehubcasepage',
            name='location_zoom',
            field=models.SmallIntegerField(blank=True, default=9, null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeCaseAttachedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('source', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='attached_datasets', to='knowledgeplatform.knowledgehubcasepage')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCaseStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('stakeholder_type', models.CharField(choices=[('authority', 'Authority'), ('citizen-science-initiative', 'Citizen Science Initiative'), ('undefined', 'Undefined')], default='undefined', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakeholders', to='knowledgeplatform.knowledgehubcasepage')),
            ],
        ),
    ]
