# Generated by Django 5.2.14 on 2026-08-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0028_knowledgehubcasepage_cgd_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgehubcasepage',
            name='policy_intro',
        ),
    ]
