# Generated by Django 5.2.14 on 2026-08-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0029_remove_knowledgehubcasepage_policy_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgehubcasepage',
            name='case_contacts',
        ),
    ]
