# Generated by Django 5.2.14 on 2026-08-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0030_remove_knowledgehubcasepage_case_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticlepage',
            name='authors',
        ),
    ]
