# Generated by Django 5.2.14 on 2026-08-26 19:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0031_remove_knowledgearticlepage_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='working_with_statistics',
            field=wagtail.fields.StreamField([('statistic', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('utils.Statistic',), {})}),
        ),
        migrations.AddField(
            model_name='knowledgehubhomepage',
            name='working_with_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
