# Generated by Django 5.2.14 on 2026-09-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0022_merge_20260901_0722'),
        ('knowledgeplatform', '0032_knowledgehubhomepage_working_with_statistics_and_more'),
    ]

    operations = [
    ]
