# Generated by Django 5.2.14 on 2026-09-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0023_knowledgehubhomepage_discover_more_page'),
        ('knowledgeplatform', '0033_merge_20260901_0738'),
    ]

    operations = [
    ]
