# Generated by Django 5.2.14 on 2026-09-10 15:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0034_merge_20260901_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticlepage',
            name='display_body',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='case_issue',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgehubcasepage',
            name='display_body',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CasePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='knowledgeplatform.knowledgehubcasepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
