# Generated by Django 5.2.14 on 2026-09-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0035_knowledgearticlepage_display_body_and_more'),
        ('utils', '0016_policytypesnippet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='utils.policysnippet'),
        ),
    ]
