# Generated by Django 5.2.14 on 2026-09-11 09:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeplatform', '0036_casepolicy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticleattachedresource',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_resources', to='knowledgeplatform.knowledgearticlepage'),
        ),
        migrations.AlterField(
            model_name='knowledgecaseattacheddataset',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_datasets', to='knowledgeplatform.knowledgehubcasepage'),
        ),
        migrations.AlterField(
            model_name='knowledgecaseattachedresource',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_resources', to='knowledgeplatform.knowledgehubcasepage'),
        ),
        migrations.AlterField(
            model_name='knowledgecasestakeholder',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='knowledgeplatform.knowledgehubcasepage'),
        ),
    ]
