# Generated by Django 5.2.14 on 2026-05-14 13:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedsAndSolutionsHubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Introductory text shown before the wizard starts.')),
            ],
            options={
                'verbose_name': 'Needs & Solutions hub wizard page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
