# Generated by Django 5.2.14 on 2026-06-30 13:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0002_question_details_optiontag_option_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsandsolutionshubpage',
            name='color_hex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='needsandsolutionshubpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description of purpose used on the homepage CTA'),
        ),
    ]
