# Generated by Django 5.2.14 on 2026-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0003_needsandsolutionshubpage_color_hex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needsandsolutionshubpage',
            name='color_hex',
            field=models.CharField(blank=True, help_text='The background color for the CTA to this page on the homepage, expressed as any valid css colour string (eg #ff0000 or rgb(1, 2, 3))', max_length=10, null=True),
        ),
    ]
