# Generated by Django 5.2.14 on 2026-07-27 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0004_alter_needsandsolutionshubpage_color_hex'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['sort_order'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sort_order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='option',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('translation_key', 'locale')},
        ),
    ]
