# Generated by Django 5.2.14 on 2026-07-29 14:39

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0005_alter_option_options_alter_question_options_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedsAndSolutionsHubIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NeedsAndSolutionsHubSurveyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Introductory text shown before the wizard starts.')),
                ('need_description', wagtail.fields.RichTextField(blank=True, help_text='The need shown in the grid on the needs and solutions hub index page')),
                ('color_hex', models.CharField(blank=True, help_text='The background color for the CTA to this page on the homepage, expressed as any valid css colour string (eg #ff0000 or rgb(1, 2, 3))', max_length=10, null=True)),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Description of purpose used on the homepage CTA')),
            ],
            options={
                'verbose_name': 'Needs & Solutions hub wizard page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NeedsAndSolutionsHubFilterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('need_description', wagtail.fields.RichTextField(blank=True, help_text='The need shown in the grid on the needs and solutions hub index page')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='needs_and_solutions_hub.OptionTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='question',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='needs_and_solutions_hub.needsandsolutionshubsurveypage'),
        ),
        migrations.DeleteModel(
            name='NeedsAndSolutionsHubPage',
        ),
    ]
