# Generated by Django 5.2.14 on 2026-07-29 14:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0007_filterpagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='needsandsolutionshubindexpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text shown above the grid of needs.'),
        ),
    ]
