# Generated by Django 5.2.14 on 2026-09-12 14:36

import modelcluster.contrib.taggit
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0008_needsandsolutionshubindexpage_intro_text'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needsandsolutionshubsurveypage',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='needsandsolutionshubsurveypage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='needsandsolutionshubindexpage',
            name='color_hex',
            field=models.CharField(blank=True, help_text='The background color for the CTA to this page on the homepage, expressed as any valid css colour string (eg #ff0000 or rgb(1, 2, 3))', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='needsandsolutionshubindexpage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description of purpose used on the homepage CTA'),
        ),
        migrations.AlterField(
            model_name='needsandsolutionshubfilterpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='needs_and_solutions_hub.FilterPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
