# Generated by Django 5.2.14 on 2026-09-12 15:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0010_needsandsolutionshubfilterpage_results_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='details',
        ),
        migrations.AddField(
            model_name='question',
            name='previous_answers_explanation',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short descriptive text summarising the previous questions asked.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='why_relevant_explanation',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short text explaining why this question is relevant.', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=wagtail.fields.RichTextField(),
        ),
    ]
