# Generated by Django 5.2.14 on 2026-09-12 16:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs_and_solutions_hub', '0011_remove_question_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needsandsolutionshubsurveypage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='previous_answers_explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short descriptive text putting the questoin in context, and if relevant, summarising the previous questions asked.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='why_relevant_explanation',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional short text explaining why this question is relevant, shown at the bottom of the page.', null=True),
        ),
    ]
