# Generated by Django 5.2.14 on 2026-05-12 11:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 10), ('cta', 20), ('statistics', 24)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'components/streamfield/blocks/heading2_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3'], 'template': 'components/streamfield/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('justify-start', 'Left'), ('justify-center', 'Center'), ('justify-end', 'Right'), ('justify-normal', 'Justify')], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('image_alt_text', 3), ('caption', 4), ('align', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'form_classname': 'title'}), 8: ('wagtail.blocks.StructBlock', [[('quote', 7), ('attribution', 4)]], {}), 9: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 6), ('quote', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page', 12), ('title', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {}), 16: ('wagtail.blocks.CharBlock', (), {}), 17: ('wagtail.blocks.StructBlock', [[('link', 15), ('title', 16)]], {}), 18: ('wagtail.blocks.StreamBlock', [[('internal', 14), ('external', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('heading', 11), ('link', 18), ('description', 19)]], {}), 21: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the heading will be hidden from view and avaliable to screen-readers only.', 'label': 'Screen reader only label', 'required': False}), 22: ('wagtail.snippets.blocks.SnippetChooserBlock', ('utils.Statistic',), {}), 23: ('wagtail.blocks.ListBlock', (22,), {'max_num': 3, 'min_num': 3}), 24: ('wagtail.blocks.StructBlock', [[('heading', 11), ('sr_only_label', 21), ('statistics', 23)]], {})}),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='image',
            field=wagtail.fields.StreamField([('image', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('justify-start', 'Left'), ('justify-center', 'Center'), ('justify-end', 'Right'), ('justify-normal', 'Justify')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('image_alt_text', 1), ('caption', 2), ('align', 3)]], {})}),
        ),
    ]
