# Generated by Django 5.2.14 on 2026-06-25 14:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
