# Generated by Django 5.2.14 on 2026-07-08 15:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articlepage_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 13), ('cta', 23), ('statistics', 27)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'components/streamfield/blocks/heading2_block.html'}), 1: ('wagtail_footnotes.blocks.RichTextBlockWithFootnotes', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'footnotes'], 'template': 'components/streamfield/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('justify-start', 'Left'), ('justify-center', 'Center'), ('justify-end', 'Right'), ('justify-normal', 'Justify')], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('image_alt_text', 3), ('caption', 4), ('align', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'form_classname': 'title'}), 8: ('wagtail.blocks.StructBlock', [[('quote', 7), ('attribution', 4)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')]}), 10: ('wagtail.blocks.RichTextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('alert_type', 9), ('text', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 6), ('quote', 8), ('alert', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('page', 15), ('title', 16)]], {}), 18: ('wagtail.blocks.URLBlock', (), {}), 19: ('wagtail.blocks.CharBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('link', 18), ('title', 19)]], {}), 21: ('wagtail.blocks.StreamBlock', [[('internal', 17), ('external', 20)]], {}), 22: ('wagtail.blocks.TextBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading', 14), ('link', 21), ('description', 22)]], {}), 24: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If checked, the heading will be hidden from view and avaliable to screen-readers only.', 'label': 'Screen reader only label', 'required': False}), 25: ('wagtail.snippets.blocks.SnippetChooserBlock', ('utils.Statistic',), {}), 26: ('wagtail.blocks.ListBlock', (25,), {'max_num': 3, 'min_num': 3}), 27: ('wagtail.blocks.StructBlock', [[('heading', 14), ('sr_only_label', 24), ('statistics', 26)]], {})}),
        ),
    ]
