# Generated by Django 5.2.14 on 2026-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletopic',
            name='color_hex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
