# Generated by Django 5.2.14 on 2026-06-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('utils', '0002_articletopic_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='bluesky_handle',
            field=models.URLField(blank=True, help_text='Bluesky url'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='youtube_handle',
            field=models.URLField(blank=True, help_text='YouTube url'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='default_sharing_text',
            field=models.URLField(blank=True, help_text='Default sharing text to use if social text has not been set on a page.'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook_app_id',
            field=models.URLField(blank=True, help_text='Facebook url'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_handle',
            field=models.URLField(blank=True, help_text='Instagram url'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin_handle',
            field=models.URLField(blank=True, help_text='Linkedin url'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='tiktok_handle',
            field=models.URLField(blank=True, help_text='Your TikTok username, e.g. katyperry'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_handle',
            field=models.URLField(blank=True, help_text='Twitter url'),
        ),
        migrations.CreateModel(
            name='FundingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eu_description', models.CharField(blank=True, max_length=255)),
                ('ukri_description', models.CharField(blank=True, max_length=255)),
                ('eu_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('ukri_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
