# Generated by Django 5.2.14 on 2026-06-26 09:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_remove_socialmediasettings_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsettings',
            name='additional_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
