# Generated by Django 5.2.14 on 2026-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_articletopic_color_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_signup_title', models.CharField(default='Sign up for our newsletter', max_length=120)),
                ('newsletter_signup_description', models.CharField(blank=True, max_length=255)),
                ('newsletter_mailchimp_api_key', models.CharField(blank=True, max_length=255)),
                ('newsletter_mailchimp_audience_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
