# Generated by Django 5.2.14 on 2026-06-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_articletopic_color_hex'),
        ('utils', '0005_newslettersetting'),
    ]

    operations = [
    ]
