# Generated by Django 5.2.14 on 2026-07-06 17:13

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_articletopic_locale_articletopic_translation_key'),
    ]

    operations = [
        BootstrapTranslatableModel('utils.ArticleTopic'),
    ]
