# Generated by Django 5.2.14 on 2026-07-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_alter_articletopic_locale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersettings',
            name='newsletter_signup_description',
        ),
        migrations.RemoveField(
            model_name='newslettersettings',
            name='newsletter_signup_title',
        ),
    ]
