# Generated by Django 5.2.14 on 2026-08-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('utils', '0011_remove_newslettersettings_newsletter_signup_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('url', models.URLField(blank=True, help_text='Contact website')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
        ),
    ]
