# Generated by Django 5.2.14 on 2026-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_casescopesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsnippet',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
