# Generated by Django 5.2.14 on 2026-09-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_articletopic_icon'),
        ('utils', '0014_contactsnippet_name'),
    ]

    operations = [
    ]
