# Generated by Django 5.2.14 on 2026-09-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('knowledgeplatform', '0035_knowledgearticlepage_display_body_and_more'),
        ('utils', '0015_merge_0012_articletopic_icon_0014_contactsnippet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTypeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactSnippet',
            new_name='CaseContactSnippet',
        ),
        migrations.CreateModel(
            name='PolicySnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL to policy text')),
                ('slug', models.SlugField(max_length=255)),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_type', to='utils.policytypesnippet')),
            ],
        ),
    ]
